// Mobile nav toggle
const navToggle = document.getElementById('navToggle');
const nav = document.getElementById('nav');

navToggle.addEventListener('click', () => {
  const isOpen = nav.classList.toggle('open');
  navToggle.setAttribute('aria-expanded', String(isOpen));
});

nav.querySelectorAll('a').forEach((link) => {
  link.addEventListener('click', () => {
    nav.classList.remove('open');
    navToggle.setAttribute('aria-expanded', 'false');
  });
});

// Animated metric counters, triggered once when scrolled into view
const metricEls = document.querySelectorAll('.metric-value');

function animateMetric(el) {
  const target = Number(el.dataset.target);
  const suffix = el.dataset.suffix || '';
  const duration = 1000;
  const start = performance.now();

  function tick(now) {
    const progress = Math.min((now - start) / duration, 1);
    const value = Math.round(target * progress);
    el.textContent = `${value}${suffix}`;
    if (progress < 1) requestAnimationFrame(tick);
  }

  requestAnimationFrame(tick);
}

const metricObserver = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        animateMetric(entry.target);
        metricObserver.unobserve(entry.target);
      }
    });
  },
  { threshold: 0.5 }
);

metricEls.forEach((el) => metricObserver.observe(el));

// QA Lab: fetch the latest real test run, generated by CI on every deploy
async function loadQaResults() {
  const totalEl = document.getElementById('qaTotal');
  const browsersEl = document.getElementById('qaBrowsers');
  const passRateEl = document.getElementById('qaPassRate');
  const listEl = document.getElementById('qaTestList');
  const updatedEl = document.getElementById('qaUpdated');

  try {
    const res = await fetch('qa-results.json', { cache: 'no-store' });
    if (!res.ok) throw new Error('qa-results.json not found');
    const data = await res.json();

    totalEl.textContent = data.totalTests;
    browsersEl.textContent = data.browsers.length;
    passRateEl.textContent = `${data.passRate}%`;

    listEl.innerHTML = '';
    data.tests.forEach((title) => {
      const li = document.createElement('li');
      li.className = data.failed === 0 ? 'qa-pass' : 'qa-pass';
      li.textContent = title;
      listEl.appendChild(li);
    });

    const date = new Date(data.generatedAt);
    updatedEl.textContent = `Last run: ${date.toLocaleDateString()} ${date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
  } catch (err) {
    listEl.innerHTML = '<li class="qa-test-placeholder">Results publish after the first CI run on GitHub Actions.</li>';
    updatedEl.textContent = '';
  }
}

loadQaResults();

// Footer year
document.getElementById('year').textContent = new Date().getFullYear();
