// Mobile nav toggle
const navToggle = document.getElementById('navToggle');
const nav = document.getElementById('nav');

navToggle.addEventListener('click', () => {
  const isOpen = nav.classList.toggle('open');
  navToggle.setAttribute('aria-expanded', String(isOpen));
});

nav.querySelectorAll('a').forEach((link) => {
  link.addEventListener('click', () => {
    nav.classList.remove('open');
    navToggle.setAttribute('aria-expanded', 'false');
  });
});

// Animated metric counters, triggered once when scrolled into view
const metricEls = document.querySelectorAll('.metric-value');

const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

function animateMetric(el) {
  const target = Number(el.dataset.target);
  const suffix = el.dataset.suffix || '';

  if (prefersReducedMotion) {
    el.textContent = `${target}${suffix}`;
    return;
  }

  const duration = 1000;
  const start = performance.now();

  function tick(now) {
    const progress = Math.min((now - start) / duration, 1);
    const value = Math.round(target * progress);
    el.textContent = `${value}${suffix}`;
    if (progress < 1) requestAnimationFrame(tick);
  }

  requestAnimationFrame(tick);
}

const metricObserver = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        animateMetric(entry.target);
        metricObserver.unobserve(entry.target);
      }
    });
  },
  { threshold: 0.5 }
);

metricEls.forEach((el) => metricObserver.observe(el));

// QA Lab: fetch the latest real test run, generated by CI on every deploy
let lastRun = null;

function renderLastRun(updatedEl) {
  if (!lastRun) return;
  const locale = window.i18n.lang === 'es' ? 'es' : undefined;
  const day = lastRun.toLocaleDateString(locale);
  const time = lastRun.toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' });
  updatedEl.textContent = `${window.i18n.t('Last run:')} ${day} ${time}`;
}

document.addEventListener('i18n:change', () => {
  renderLastRun(document.getElementById('qaUpdated'));
});

async function loadQaResults() {
  const totalEl = document.getElementById('qaTotal');
  const browsersEl = document.getElementById('qaBrowsers');
  const passRateEl = document.getElementById('qaPassRate');
  const listEl = document.getElementById('qaTestList');
  const updatedEl = document.getElementById('qaUpdated');

  try {
    const res = await fetch('qa-results.json', { cache: 'no-store' });
    if (!res.ok) throw new Error('qa-results.json not found');
    const data = await res.json();

    totalEl.textContent = data.totalTests;
    browsersEl.textContent = data.browsers.length;
    passRateEl.textContent = `${data.passRate}%`;

    listEl.innerHTML = '';
    data.tests.forEach((t) => {
      const li = document.createElement('li');
      li.className = t.passed ? 'qa-pass' : 'qa-fail';
      li.textContent = t.title;
      listEl.appendChild(li);
    });

    lastRun = new Date(data.generatedAt);
    renderLastRun(updatedEl);
  } catch (err) {
    const li = document.createElement('li');
    li.className = 'qa-test-placeholder';
    li.textContent = window.i18n.t('Results publish after the first CI run on GitHub Actions.');
    listEl.innerHTML = '';
    listEl.appendChild(li);
    updatedEl.textContent = '';
  }
}

loadQaResults();

// Footer year
document.getElementById('year').textContent = new Date().getFullYear();
